some changes
rawen554/gophkeeper pull request #1
Opened 2023-10-25 07:58 UTC by rawen554

2023-10-28 19:07 UTC, s-shpak requested changes
1. Если ты проектируешь REST-интерфейс, то не забудь об OpenAPI
2. Посмотри в чате, как лучше выстроить схему взаимодействия с твоим сервисом
3. Я бы советовал тебе делать твой клиент не с TUI, а с CLI (можно использовать cobra: https://github.com/spf13/cobra)

Вектор развития проекта нормальный, начинай писать логику клиента. Добейся того, чтобы клиент мог сохранять данные и забирать их с сервера (и из кеша), и можно будет обсудить дальнейшие шаги

2023-10-28 19:07 UTC, s-shpak commented on cmd/client/main.go
> +		panic(err)
Не надо паниковать

2023-10-28 19:07 UTC, s-shpak commented on internal/adapters/store/migrations/00002_data_type_init.down.sql
1. А где остаток определения схемы БД?
2. Лучше начни нумерацию с `00001`

2023-10-28 19:07 UTC, s-shpak commented on internal/app/app_test.go
> +// func TestLogin(t *testing.T) {
deadcode ?

2023-11-02 14:56 UTC, s-shpak requested changes
Все ок, реализуй логику. Что тебе обязательно нужно:
1. сделать отправку данных на сервер и их получение
2. хранение данных в кеше (который может быть только в файловой системе или в памяти и в файловой системе)
3. read-only режим, если нет соединения с сервером
Также добавь инструкции по запуску (и тестированию) сервиса локально

2023-11-07 21:53 UTC, rawen554 commented
Добавил все, кроме тестов. Посмотри, пожалуйста, по логике, достаточно ли будет этого функционала. И приступлю к написанию тестов.

2023-11-08 12:26 UTC, s-shpak requested changes

2023-11-08 12:26 UTC, s-shpak commented on Makefile
1. Почему бы инициализацию БД не поместить в docker-compose ?
2. БД сообщает о следующей ошибке: `gophkeeper-gophkeeper-db-1  | 2023-11-08 12:18:38.507 UTC [58] FATAL:  role "root" does not exist`. С чем это связано и как это исправить (думаю, что надо посмотреть на healthcheck)?

2023-11-08 12:26 UTC, s-shpak commented on .DS_Store
Это надо убрать из репозитория

2023-11-08 12:26 UTC, s-shpak commented on README.md
Добавь в README пример работы с сервисом: я пока, вроде, залогировался, но токен не получил и не могу добавить записи в сервис, т.к. мне сообщается `error: no auth data, login first`

2023-11-08 22:13 UTC, rawen554 commented on Makefile
Инициализация и так проходила через монтирование папки с init.sql к /docker-entrypoint-initdb.d.
Починил healthcheck.

2023-11-08 22:14 UTC, rawen554 commented on README.md
Обновил README.
Пофиксил баги, сейчас все должно работать как ожидается.

2023-11-10 10:18 UTC, s-shpak requested changes

2023-11-10 10:18 UTC, s-shpak commented on cmd/client/bin/client_darwin64
Убери этот и другие бинари из репозитория, пожалуйста

2023-11-10 10:18 UTC, s-shpak commented on cmd/client/internal/client/client.go
> +				fmt.Println("empty API URL")
Не используй `fmt.*` в коде

2023-11-10 15:16 UTC, s-shpak approved these changes

2023-11-13 11:42 UTC, merged